# Generated by Django 5.2.15 on 2026-06-24 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('movies', '0001_initial'),
        ('theaters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_seats', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='theaters.seat'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='showtime',
            name='screen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showtimes', to='theaters.screen'),
        ),
        migrations.AddField(
            model_name='bookingseat',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_seats', to='bookings.showtime'),
        ),
        migrations.AddField(
            model_name='booking',
            name='showtime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.showtime'),
        ),
        migrations.AddConstraint(
            model_name='bookingseat',
            constraint=models.UniqueConstraint(fields=('showtime', 'seat'), name='unique_showtime_seat'),
        ),
    ]
