databases:
  - name: movie-ticket-db
    databaseName: movie_ticket
    user: movie_ticket
    plan: free

services:
  - type: web
    name: movie-ticket-api
    runtime: python
    rootDir: backend
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movie-ticket-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CITY_NAME
        value: YourCity
      - key: ALLOWED_HOSTS
        value: movie-ticket-api.onrender.com

  - type: web
    name: movie-ticket-web
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: movie-ticket-api
          envVarKey: RENDER_EXTERNAL_URL
